let handler = async (m, { conn }) => {

let iya = kata.getRandom()
let txtnya = `${iya.quote}\n\n*Anime;* ${iya.anime}\n*Karakter:* ${iya.character}\n*Deksripsi:* ${iya.description}\n*Url:* ${iya.image}`
m.reply(txtnya)
}
handler.menuanime = ['katanime']
handler.tagsanime = ['randompic']
handler.command = /^(katanime|kataanime)$/i

handler.premium = true
handler.limit = true

export default handler

// Tambah aja sendiri sisanya 
// Ini gw bikin ya tot bukn maling atau colong dari sc orang -_
const kata = [
  {
  "anime": "Naruto",
  "character": "Uzumaki Naruto",
  "quote": "Jika kamu tidak mau mengambil risiko, kamu tidak akan pernah tahu betapa hebatnya kamu.",
  "image": "https://myanimelist.net/character/20/Naruto_Uzumaki",
  "description": "Naruto adalah anime yang menceritakan tentang seorang ninja muda bernama Naruto Uzumaki, yang berjuang untuk menjadi Hokage (pemimpin desa) dan melindungi orang-orang yang dicintainya dari kejahatan.",
  },
  {
  "anime": "One Piece",
  "character": "Monkey D. Luffy",
  "quote": "Jika kamu menyerah, artinya kamu tidak pantas menjadi Raja Bajak Laut!",
  "image": "https://myanimelist.net/character/42/Monkey_D_Luffy",
  "description": "One Piece adalah anime yang mengikuti petualangan Monkey D. Luffy, seorang bajak laut yang mencari harta karun legendaris bernama One Piece untuk menjadi Raja Bajak Laut.",
  },
  {
  "anime": "Attack on Titan",
  "character": "Eren Yeager",
  "quote": "Jika kamu ingin mengenal kebenaran, jangan takut untuk menghadapinya, meskipun kebenaran itu mengerikan.",
  "image": "https://myanimelist.net/character/258/Monkey_D_Luffy",
  "description": "Attack on Titan adalah anime yang mengisahkan tentang dunia di mana manusia terancam oleh mahluk raksasa yang dikenal sebagai Titan. Eren Yeager merupakan salah satu protagonis yang berjuang untuk melindungi umat manusia dari ancaman Titans.",
  },
  {
  "anime": "Fullmetal Alchemist: Brotherhood",
  "character": "Edward Elric",
  "quote": "Ketika kamu mencintai seseorang, dan mereka akan meninggalkanmu, atau bahkan mati, itu adalah aib sebagai manusia bagaimana kamu tidak turut merasakannya.",
  "image": "https://myanimelist.net/character/17/Edward_Elric",
  "description": "Fullmetal Alchemist: Brotherhood adalah anime yang mengikuti petualangan dua saudara laki-laki, Edward dan Alphonse Elric, yang berusaha untuk memperbaiki kesalahan mereka dalam menggunakan ilmu alkimia yang terlarang.",
  },
  {
  "anime": "Death Note",
  "character": "L Lawliet",
  "quote": "Kadang-kadang, menakut-nakuti orang adalah satu-satunya cara untuk membuat mereka mendengarkan.",
  "image": "https://myanimelist.net/character/6/L_Lawliet",
  "description": "Death Note adalah anime yang menceritakan tentang seorang siswa yang menemukan buku kematian misterius yang memungkinkannya membunuh orang-orang dengan hanya menuliskan nama mereka di dalamnya. L Lawliet adalah seorang detektif jenius yang berusaha untuk menangkap pembunuh tersebut.",
  },
  {
  "anime": "Hunter x Hunter",
  "character": "Gon Freecss",
  "quote": "Jika kamu ingin benar-benar memahami seseorang, lihatlah sekelilingnya dulu.",
  "image": "https://myanimelist.net/character/423/Gon_Freecss",
  "description": "Hunter x Hunter adalah anime yang mengisahkan perjalanan seorang bocah bernama Gon Freecss yang menjadi Hunter, seorang pemburu yang memiliki hak istimewa dan melakukan berbagai macam tugas, seperti menjaga keseimbangan dunia atau mencari harta karun.",
  },
  {
  "anime": "My Hero Academia",
  "character": "All Might",
  "quote": "Bertemanlah dengan kegelapan, tetapi jangan pernah kau leburnya, karena itu akan menghancurkanmu.",
  "image": "https://myanimelist.net/character/8973/Toshinori_Yagi",
  "description": "My Hero Academia adalah anime yang berlatar di dunia di mana hampir semua orang memiliki kekuatan super. All Might adalah seorang pahlawan super terkenal yang memberikan kekuatannya kepada seorang siswa bernama Izuku Midoriya untuk menjadi pahlawan baru.",
  },
  {
  "anime": "Kimi no Na wa. (Your Name)",
  "character": "Taki Tachibana",
  "quote": "Mimpilah tentang masa depan, tetapi jangan pernah melupakan saat ini.",
  "image": "https://myanimelist.net/character/130000/Taki_Tachibana",
  "description": "Kimi no Na wa. adalah anime yang mengisahkan tentang dua orang yang secara misterius bertukar tubuh mereka ketika mereka tidur. Taki Tachibana adalah salah satu dari dua protagonis yang berusaha untuk menemukan kebenaran di balik pertukaran aneh ini.",
  },
  {
  "anime": "Sword Art Online",
  "character": "Kirito",
  "quote": "Ketika kamu melawan monster dalam permainan, kamu tidak perlu percaya padaku... Percayalah padamu sendiri!",
  "image": "https://myanimelist.net/character/22389/Kirito",
  "description": "Sword Art Online adalah anime yang berlatar di dunia virtual reality, di mana para pemain terjebak dalam permainan dan harus mencapai level tertinggi untuk keluar. Kirito adalah seorang pemain yang berpengalaman yang berjuang untuk bertahan hidup di dunia maya tersebut.",
  },
  {
  "anime": "Fairy Tail",
  "character": "Natsu Dragneel",
  "quote": "Sekalipun hidup dengan membenci sesuatu, sebenarnya kamu masih menganggapnya penting. Sebaliknya, jika kamu benar-benar menyukai sesuatu, maka tidak akan ada kompromi.",
  "image": "https://myanimelist.net/character/28/Natsu_Dragneel",
  "description": "Fairy Tail adalah anime yang mengisahkan tentang petualangan sebuah kelompok penyihir muda yang tergabung dalam guild bernama Fairy Tail. Natsu Dragneel adalah salah satu anggota kelompok tersebut yang memiliki kemampuan menggunakan sihir api.",
  },
  {
  "anime": "Naruto Shippuden",
  "character": "Uzumaki Naruto",
  "quote": "Orang yang benar-benar kuat adalah bukan yang tidak pernah merasa lemah, tetapi yang terus berjuang meskipun dihancurkan oleh kesedihan.",
  "image": "https://cdn.myanimelist.net/images/characters/8/50411",
  "description": "Naruto Shippuden adalah sekuel dari anime Naruto yang menceritakan perjuangan Naruto dalam menjadi seorang Hokage. Quote ini mengajarkan bahwa kekuatan sejati timbul dari kegigihan untuk berdiri kembali meskipun mengalami kesedihan yang mendalam.",
  },
  {
  "anime": "One Piece",
  "character": "Monkey D. Luffy",
  "quote": "Jika kamu tidak berani memulai, kamu pasti tidak akan pernah tahu seberapa jauh kamu bisa pergi.",
  "image": "https://cdn.myanimelist.net/images/characters/16/135629",
  "description": "One Piece adalah anime tentang petualangan Monkey D. Luffy dan kru bajak laut Topi Jerami mencari harta karun terbesar, One Piece. Quote ini menginspirasi untuk mengatasi ketakutan dalam memulai sesuatu, karena hanya dengan memulai kita dapat mengetahui potensi yang sebenarnya.",
  },
  {
  "anime": "Attack on Titan",
  "character": "Erwin Smith",
  "quote": "Hanya dengan melangkah maju, kita dapat menemukan arah dan tujuan yang sebenarnya.",
  "image": "https://cdn.myanimelist.net/images/characters/8/229546",
  "description": "Attack on Titan mengisahkan peperangan manusia melawan para raksasa. Quote ini mengajarkan bahwa dalam perjalanan hidup, kita harus berani melangkah maju, bahkan jika kita tidak yakin, karena hanya dengan melangkah maju kita dapat menemukan tujuan yang sebenarnya.",
  },
  {
  "anime": "Fullmetal Alchemist: Brotherhood",
  "character": "Edward Elric",
  "quote": "Ketika kamu menyadari apa yang hilang, kamu akan merasa betapa berharganya apa yang kamu miliki.",
  "image": "https://cdn.myanimelist.net/images/characters/6/10185",
  "description": "Fullmetal Alchemist: Brotherhood adalah anime tentang petualangan Edward dan Alphonse Elric dalam mencari Batu Bertuah untuk mengembalikan tubuh mereka yang hilang. Quote ini mengajarkan kita untuk menghargai apa yang kita miliki dan untuk tidak mengambil hal-hal tersebut sebagai kepastian.",
  },
  {
  "anime": "Death Note",
  "character": "L Lawliet",
  "quote": "Bahkan orang jahat pun bisa melakukan sesuatu yang baik. Seorang sainswan menemukan obat yang menyembuhkan penyakit, namun ia juga bisa menggunakan temuannya itu untuk bakteri penginfeksi yang menyerang manusia.",
  "image": "https://cdn.myanimelist.net/images/characters/13/42155",
  "description": "Death Note adalah cerita tentang Light Yagami yang menemukan buku yang dapat membunuh siapa pun yang namanya ditulis di dalamnya. Quote ini mengajarkan bahwa seseorang bersifat netral, dan kebaikan atau kejahatan bergantung pada cara mereka menggunakan kekuatan mereka.",
  },
  {
  "anime": "Your Lie in April",
  "character": "Kousei Arima",
  "quote": "Bahagia adalah sesuatu yang datang dan pergi, tapi jika kamu punya keberanian, kamu bisa mendapatkannya kembali.",
  "image": "https://cdn.myanimelist.net/images/characters/10/268789",
  "description": "Your Lie in April adalah kisah Kousei Arima, seorang pianis yang kehilangan kemampuan untuk mendengar musik setelah kematian ibunya. Quote ini mengajarkan bahwa bahagia adalah sesuatu yang tidak abadi, namun dengan keberanian dan tekad, kita dapat mencari dan mendapatkan kembali kebahagiaan yang hilang.",
  },
  {
  "anime": "Haikyuu!!",
  "character": "Hinata Shouyou",
  "quote": "Tak ada yang tahu apa yang akan terjadi di masa depan. Maka, yang bisa kita lakukan adalah berusaha sebaik mungkin di masa kini.",
  "image": "https://cdn.myanimelist.net/images/characters/11/316282",
  "description": "Haikyuu!! adalah anime tentang tim voli SMA Karasuno yang berjuang untuk mencapai kejuaraan nasional. Quote ini mengajarkan kita untuk fokus pada saat ini dan berusaha sebaik mungkin, karena kita tidak dapat meramalkan masa depan dan hanya dapat mengendalikan apa yang sedang kita lakukan saat ini.",
  },
  {
  "anime": "Sword Art Online",
  "character": "Kirito",
  "quote": "Dalam situasi apapun, jangan pernah kehilangan harapan.",
  "image": "https://cdn.myanimelist.net/images/characters/5/216092",
  "description": "Sword Art Online adalah cerita tentang Kirito yang terperangkap dalam sebuah permainan VRMMORPG. Quote ini mengajarkan kita untuk tetap optimis dan tidak pernah kehilangan harapan, bahkan dalam situasi yang sulit sekalipun.",
  },
  {
  "anime": "Dragon Ball Z",
  "character": "Goku",
  "quote": "Jangan menyerah. Seperti kata-kata Kaio-Sama, gunung tertinggi pun bisa diukur langkah demi langkah.",
  "image": "https://cdn.myanimelist.net/images/characters/11/43663",
  "description": "Dragon Ball Z adalah anime tentang petualangan Goku untuk melindungi bumi dari ancaman jahat. Quote ini mengajarkan kita untuk tidak menyerah dan mengambil setiap langkah kecil untuk mencapai tujuan besar, karena bahkan hal yang tampak tidak mungkin dapat dicapai dengan kerja keras dan ketekunan.",
  },
  {
  "anime": "Demon Slayer",
  "character": "Kamado Tanjirou",
  "quote": "Kesedihan dan keputusasaan tidak akan membawa apa-apa. Hanya dengan terus bergerak maju, kita bisa menemukan kebahagiaan.",
  "image": "https://cdn.myanimelist.net/images/characters/15/408618",
  "description": "Demon Slayer mengisahkan petualangan Tanjirou untuk membalas dendam pada ibunya yang tewas oleh iblis. Quote ini mengajarkan kita untuk tidak terpuruk dalam kesedihan dan keputusasaan, namun terus bergerak maju dengan harapan untuk menemukan kebahagiaan di masa depan.",
  },
  {
    "anime": "Attack on Titan",
    "karakter": "Levi Ackerman",
    "quote": "Dalam dunia yang kejam ini, hanya yang terkuat yang bertahan.",
    "image": "https://myanimelist.net/character/45627/Levi",
    "description": "Kata mutiara ini menggambarkan tekad dan kekuatan yang dimiliki oleh Levi Ackerman dalam menghadapi situasi yang sulit di anime Attack on Titan. Meskipun hidup di dunia yang kejam, ia menggambarkan pentingnya menjadi kuat untuk melindungi dan bertahan hidup.",
  },
  {
    "anime": "Naruto",
    "karakter": "Hatake Kakashi",
    "quote": "Seorang guru tak boleh merasa putus asa bahkan pada muridnya yang paling bodoh sekalipun.",
    "image": "https://myanimelist.net/character/6/Kakashi_Hatake",
    "description": "Kata mutiara ini menggambarkan dedikasi Kakashi Hatake dalam perannya sebagai guru di anime Naruto. Ia mengajarkan pentingnya kesabaran dan ketekunan dalam mendidik semua muridnya, tanpa memandang kecerdasan atau kekurangan mereka.",
  },
  {
    "anime": "One Piece",
    "karakter": "Monkey D. Luffy",
    "quote": "Hidup kan menjadi lebih mudah jika Anda mengikuti hati Anda sendiri.",
    "image": "https://myanimelist.net/character/54/Monkey_D_Luffy",
    "description": "Kata mutiara ini mencerminkan sifat kepala batu namun penuh semangat dari Monkey D. Luffy dalam anime One Piece. Luffy selalu mengikuti hatinya, tidak peduli berapa kali dia harus menghadapi rintangan atau penolakan, karena ia yakin bahwa jika ia mengikuti impian dan keinginannya sendiri, hidupnya akan lebih berarti.",
  },
  {
    "anime": "Fullmetal Alchemist",
    "karakter": "Edward Elric",
    "quote": "Kesedihan adalah perasaan yang diberikan pada manusia, sehingga mereka bisa memahami arti kebahagiaan.",
    "image": "https://myanimelist.net/character/11/Edward_Elric",
    "description": "Kata mutiara ini menggambarkan pertumbuhan dan kedalaman karakter Edward Elric dalam anime Fullmetal Alchemist. Meskipun menghadapi penderitaan dan tragedi, Ed belajar untuk menghadapinya dan menggunakan pengalaman tersebut untuk menghargai momen-momen bahagia dalam hidupnya.", 
  },
  {
    "anime": "Death Note",
    "karakter": "L Lawliet",
    "quote": "Kadang-kadang, perbuatan yang salah dianggap benar hanya karena dibenarkan oleh mayoritas.",
    "image": "https://myanimelist.net/character/170/L_Lawliet",
    "description": "Kata mutiara ini memvisualisasikan karakter L Lawliet dalam Death Note. Ia adalah seorang detektif jenius yang memiliki pandangan yang kritis terhadap moralitas dan etika, menyadarkan kita bahwa kebenaran tidak selalu ditentukan oleh mayoritas, dan penting untuk selalu mempertanyakan dan memahami alasan di balik apa yang diterima oleh masyarakat.",
  },
  {
    "anime": "One Punch Man",
    "karakter": "Saitama",
    "quote": "Kadang-kadang, kebahagiaan bisa ditemukan di tempat yang tak terduga.",
    "image": "https://myanimelist.net/character/91821/Saitama",
    "description": "Kata mutiara ini mencerminkan pemikiran santai dan positif dari Saitama dalam One Punch Man. Meskipun ia adalah pahlawan yang tak terkalahkan, ia menemukan kebahagiaan dalam hal-hal sederhana dan tidak terduga dalam kehidupan sehari-harinya, mengilustrasikan pentingnya menghargai hal-hal kecil dalam hidup.",
  },
  {
    "anime": "My Hero Academia",
    "karakter": "All Might",
    "quote": "Jika Anda mengemban kekuatan yang besar, itu adalah tanggung jawab Anda untuk melindungi yang lemah.",
    "image": "https://myanimelist.net/character/54667/All_Might",
    "description": "Kata mutiara ini mewakili prinsip dasar dari All Might dalam My Hero Academia. Sebagai simbol perdamaian dan keadilan, ia mengajarkan pentingnya menggunakan kekuasaan untuk melindungi orang-orang yang lebih lemah dan terancam. Ia mendorong kita untuk bertanggung jawab atas kekuatan yang kita miliki untuk membantu orang lain.",
  },
  {
    "anime": "Dragon Ball Z",
    "karakter": "Goku",
    "quote": "Jika Anda pikir hanya dengan menyerah, itu akan selesai. Tidak ada gunanya mengambil jalan pintas.",
    "image": "https://myanimelist.net/character/44/Goku",
    "description": "Kata mutiara ini mencerminkan semangat dan tekad Goku dalam Dragon Ball Z. Meskipun ia sering kali menghadapi kekalahan dan rintangan yang sulit, ia tidak pernah menyerah dan terus mencoba dengan tenaga dan kehendaknya. Ini mengingatkan kita untuk tidak pernah mengambil jalan pintas dalam menghadapi tantangan dan tetap gigih dalam mencapai tujuan.",
  },
  {
    "anime": "Bleach",
    "karakter": "Ichigo Kurosaki",
    "quote": "Hidup adalah perjalanan yang harus dijalani, tidak peduli betapa pahit atau menyakitkannya.",
    "image": "https://myanimelist.net/character/3/Ichigo_Kurosaki",
    "description": "Kata mutiara ini menggambarkan transformasi karakter Ichigo Kurosaki dalam anime Bleach. Ia menyadari bahwa hidup adalah perjalanan yang penuh dengan keberhasilan dan kegagalan, kegembiraan dan kesedihan. Dalam menghadapi situasi yang sulit, ia belajar untuk menerima dan terus maju, memahami bahwa melalui perjuangan kita bisa tumbuh.",
  },
  {
    "anime": "Code Geass",
    "character": "Lelouch Lamperouge",
    "quote": "Aku akan menjadi impiannya yang menjadi nyata, bahkan jika darah pejuangku harus kupergunakan demi mencapainya.",
    "image": "https://myanimelist.net/character/137/Lelouch_Lamperouge",
    "description": "Kata mutiara ini mencerminkan tekad dan keberanian Lelouch Lamperouge dalam Code Geass. Ia siap mengorbankan segalanya, bahkan nyawa dan moralitasnya, untuk mencapai tujuan dan memberikan kehidupan yang lebih baik bagi orang-orang yang dicintainya. Ia mengajarkan kita tentang pentingnya memiliki visi dan tekad yang kuat.",
  },
  {
  "anime": "Naruto",
  "character": "Naruto Uzumaki",
  "quote": "Jika kau tak bisa melindungi temanmu, bagaimana kau bisa melindungi desamu?",
  "image": "https://myanimelist.net/character/1/Naruto_Uzumaki",
  "description": "Anime Naruto menceritakan tentang seorang ninja bernama Naruto Uzumaki yang berjuang untuk melindungi desanya dari ancaman musuh. Naruto menginspirasi dengan kata-katanya yang menggambarkan pentingnya persahabatan dan keberanian.",
  },
  {
  "anime": "One Piece",
  "character": "Roronoa Zoro",
  "quote": "Jika harus mati, aku ingin mati sambil tertawa dan berdiri tegap!",
  "image": "https://myanimelist.net/character/35/Roronoa_Zoro",
  "description": "Anime One Piece mengikuti petualangan Monkey D. Luffy dan krunya untuk mencari harta karun legendaris One Piece. Roronoa Zoro adalah seorang pedang yang tangguh dan kata-katanya memperlihatkan semangat juang tanpa takut akan bahaya.",
  },
  {
  "anime": "Attack on Titan",
  "character": "Eren Yeager",
  "quote": "Kita harus terus maju, meski hanya melangkah lambat. Selama kita tidak berhenti, suatu saat kita pasti tiba di tujuan.",
  "image": "https://myanimelist.net/character/39161/Eren_Yeager",
  "description": "Anime Attack on Titan mengambil setting dunia yang dikuasai oleh para raksasa pemakan manusia. Eren Yeager adalah seorang protagonis yang melakukan perlawanan dengan tekad yang kuat dan kata-katanya menggambarkan semangat untuk terus berjuang.",
  },
  {
  "anime": "Fullmetal Alchemist: Brotherhood",
  "character": "Edward Elric",
  "quote": "Ketika kau mengira kau telah kehilangan segalanya, kau akan menemukan sesuatu yang berharga di dalam kehilanganmu.",
  "image": "https://myanimelist.net/character/5/Edward_Elric",
  "description": "Anime Fullmetal Alchemist: Brotherhood mengisahkan tentang petualangan bersaudara Elric dalam mencari batu filosofis untuk mengembalikan tubuh mereka yang hilang. Edward Elric adalah seorang alkemis yang penuh semangat dan kata-katanya menggambarkan makna di balik kegagalan dan kehilangan.",
  },
  {
  "anime": "Death Note",
  "character": "L Lawliet",
  "quote": "Dalam dunia ini, cerdas dan bodoh berbagi satu karakteristik yang sama: mereka tidak bisa mengubah pikiran orang lain.",
  "image": "https://myanimelist.net/character/13/L_Lawliet",
  "description": "Anime Death Note berkisah tentang seorang pelajar yang menemukan sebuah buku yang bisa membunuh orang hanya dengan menuliskan namanya di dalamnya. L Lawliet adalah seorang detektif jenius yang berusaha untuk mengungkap misteri di balik buku tersebut dan kata-katanya menggambarkan kebenaran tentang manusia.",
  },
  {
  "anime": "One Punch Man",
  "character": "Saitama",
  "quote": "Meski hidup terasa monoton dan datar, jangan pernah menyerah dalam mengejar impianmu.",
  "image": "https://myanimelist.net/character/97395/Saitama",
  "description": "Anime One Punch Man mengisahkan tentang Saitama, seorang pahlawan super yang mampu mengalahkan musuhnya dengan satu pukulan saja. Meski hidupnya terasa membosankan, Saitama menginspirasi dengan kata-katanya yang menekankan pentingnya tetap berjuang dan tidak menyerah.",
  },
  {
  "anime": "My Hero Academia",
  "character": "All Might",
  "quote": "Tidak ada kekuatan yang sempurna di dunia ini. Setiap kekuatan memiliki kelemahan yang harus kita terima dan kita atasi.",
  "image": "https://myanimelist.net/character/110601/All_Might",
  "description": "Anime My Hero Academia mengambil setting dunia di mana hampir semua orang memiliki kekuatan super. All Might adalah seorang pahlawan terkenal yang mengajarkan pentingnya menerima dan mengatasi kelemahan dalam diri kita.",
  },
  {
  "anime": "Hunter x Hunter",
  "character": "Gon Freecss",
  "quote": "Orang yang menyerah tidak bisa memenangkan pertarungan. Seseorang yang bertahan adalah pemenangnya.",
  "image": "https://myanimelist.net/character/425/Gon_Freecss",
  "description": "Anime Hunter x Hunter mengisahkan tentang petualangan Gon Freecss dalam mencari ayahnya yang merupakan seorang Hunter profesional. Gon adalah seorang pemuda yang penuh semangat dan kata-katanya menggambarkan tekad untuk tidak menyerah dalam menghadapi rintangan.",
  },
  {
  "anime": "Fairy Tail",
  "character": "Natsu Dragneel",
  "quote": "Jangan menyia-nyiakan waktu dengan menyesali keputusan masa lalumu. Jadilah lebih baik dari sebelumnya!",
  "image": "https://myanimelist.net/character/66/Natsu_Dragneel",
  "description": "Anime Fairy Tail berkisah tentang petualangan Natsu Dragneel, seorang penyihir naga angin, dan guild Fairy Tail. Natsu adalah seorang pemuda yang optimis dan kata-katanya menginspirasi untuk tidak terjebak dalam penyesalan dan terus berusaha menjadi versi terbaik dari diri sendiri.",
  },
  {
  "anime": "Sword Art Online",
  "character": "Kirito",
  "quote": "Ketika kita berjalan sendirian, kita bergerak paling jauh.",
  "image": "https://myanimelist.net/character/25881/Kirito",
  "description": "Anime Sword Art Online mengisahkan tentang Kirito, seorang pemain solo yang terperangkap dalam game virtual reality. Kata-kata Kirito menggambarkan rasa tanggung jawab dan kemandirian dalam mencapai tujuan.",
  },
  {
  "anime": "One Piece",
  "character": "Monkey D. Luffy",
  "quote": "Jangan pernah menyerah dalam mencapai impianmu!",
  "image": "https://myanimelist.net/character/54/Monkey_D_Luffy",
  "description": "One Piece adalah sebuah anime tentang petualangan bajak laut Monkey D. Luffy dan kru Topi Jerami dalam mencari harta karun legendaris bernama One Piece. Luffy, sebagai tokoh utama, mempunyai semangat dan tekad yang tinggi untuk mencapai impian menjadi Raja Bajak Laut.",
  },
  {
  "anime": "Naruto",
  "character": "Uzumaki Naruto",
  "quote": "Kemauan keras adalah kekuatan terbesar seseorang.",
  "image": "https://myanimelist.net/character/4/Naruto_Uzumaki",
  "description": "Naruto adalah anime tentang seorang ninja muda bernama Naruto Uzumaki yang memiliki semangat juang yang tak tergoyahkan. Di tengah kemiskinan dan kesepian, ia berusaha untuk menjadi Hokage, pemimpin Desa Konoha, dan membuktikan kepada semua orang bahwa ia bukanlah orang yang sia-sia.",
  },
  {
  "anime": "Haikyuu!!",
  "character": "Hinata Shouyou",
  "quote": "Tidak peduli seberapa tinggi lawanmu, jika kamu tidak melompat, kamu tidak akan bisa mengambil bola itu.",
  "image": "https://myanimelist.net/character/85895/Shouyou_Hinata",
  "description": "Haikyuu!! adalah anime tentang klub voli SMA Karasuno yang berusaha menjadi yang terbaik di prefektur mereka. Hinata Shouyou, sebagai tokoh utama, memiliki tinggi badan yang kurang ideal sebagai pemain voli, namun ia memiliki semangat dan kegigihan yang luar biasa dalam menggapai impiannya.",
  },
  {
  "anime": "Attack on Titan",
  "character": "Eren Yeager",
  "quote": "Orang yang membenci monster tidak perlu menjadi monster.",
  "image": "https://myanimelist.net/character/58831/Eren_Yeager",
  "description": "Attack on Titan mengisahkan tentang dunia yang dihuni oleh raksasa pemakan manusia yang disebut sebagai Titan. Eren Yeager, sebagai protagonis utama, bersumpah untuk memusnahkan semua Titan dan melindungi umat manusia. Di tengah terjebaknya dalam konflik yang kompleks, pesan motivasi ini mengingatkan kita untuk tidak terjebak dalam siklus kebencian dan kekerasan.",
  },
  {
  "anime": "Fullmetal Alchemist: Brotherhood",
  "character": "Edward Elric",
  "quote": "Kesalahan yang tidak diakui hanya akan membuatmu terjebak dalam siklus yang sama.",
  "image": "https://myanimelist.net/character/7/Edward_Elric",
  "description": "Fullmetal Alchemist: Brotherhood adalah anime tentang petualangan dua bersaudara, Edward dan Alphonse Elric, dalam mencari batu filosofis untuk mengembalikan tubuh mereka yang hilang. Edward Elric, dengan tekadnya yang kuat, mengingatkan kita pentingnya mengakui kesalahan untuk dapat berkembang dan melampaui batasan.",
  },
  {
  "anime": "Death Note",
  "character": "L Lawliet",
  "quote": "Kebenaran tidak ada artinya bagi mereka yang tidak mampu memahaminya.",
  "image": "https://myanimelist.net/character/6/L_Lawliet",
  "description": "Death Note mengisahkan tentang seorang pelajar bernama Light Yagami yang menemukan sebuah buku yang memiliki kemampuan untuk membunuh siapa saja yang namanya ditulis di dalamnya. L Lawliet, seorang detektif jenius, menjadi penantang Light dalam permainan catur intelektual. Perkataannya ini mengingatkan kita bahwa kebenaran tidak dapat dipahami tanpa kemampuan untuk mempertanyakan dan mencari pemahaman yang lebih dalam.",
  },
  {
  "anime": "Your Lie in April",
  "character": "Kousei Arima",
  "quote": "Menghadapi rasa takut adalah langkah pertama dalam mengatasi kesulitanmu.",
  "image": "https://myanimelist.net/character/74847/Kousei_Arima",
  "description": "Your Lie in April menceritakan tentang seorang pianis muda jenius bernama Kousei Arima yang kehilangan kemampuan untuk mendengar nada setelah kehilangan ibunya. Ia berjuang untuk menemukan kembali hasrat dan semangatnya dalam musik dengan bantuan seorang vionis, Kaori Miyazono. Kousei mengajarkan kita pentingnya menghadapi rasa takut dalam meraih kebahagiaan dan mengatasi kesulitan dalam hidup.",
  },
  {
  "anime": "Kimetsu no Yaiba",
  "character": "Kamado Tanjirou",
  "quote": "Karena aku melindungi mereka, aku harus menjadi lebih kuat!",
  "image": "https://myanimelist.net/character/166900/Tanjirou_Kamado",
  "description": "Kimetsu no Yaiba mengikuti perjalanan Tanjirou Kamado setelah keluarganya terbantai oleh iblis dan adiknya, Nezuko, berubah menjadi iblis. Tanjirou bersumpah untuk melindungi manusia dan mencari obat untuk mengembalikan keadaan Nezuko sebagai manusia. Perkataannya ini mencerminkan tekad dan tanggung jawab Tanjirou dalam melindungi orang-orang yang dicintainya.",
  },
  {
  "anime": "Sword Art Online",
  "character": "Kirigaya Kazuto (Kirito)",
  "quote": "Hidup itu mudah, hidup saja yang sukar.",
  "image": "https://myanimelist.net/character/34437/Kazuto_Kirigaya",
  "description": "Sword Art Online berlatar di dunia virtual reality di mana para pemain terperangkap dalam game yang mematikan. Kirigaya Kazuto, yang lebih dikenal sebagai Kirito di dalam game, adalah seorang pemain solo yang handal dan bertekad untuk memenangkan permainan dan menyelamatkan dirinya serta pemain lainnya. Kata-katanya mengingatkan kita bahwa hidup itu tidak selalu mudah, tetapi kita harus tetap berjuang dan bertahan.",
  },
  {
  "anime": "Kimi no Na wa",
  "character": "Tachibana Taki dan Miyamizu Mitsuha",
  "quote": "Walaupun kita terpisah oleh waktu dan ruang, kita pasti akan bertemu suatu hari nanti.",
  "image": "https://myanimelist.net/character/124740/Mitsuha_Miyamizu",
  "description": "Kimi no Na wa mengisahkan tentang Tachibana Taki dan Miyamizu Mitsuha, dua remaja yang terpisah oleh waktu dan ruang tetapi terhubung melalui pertukaran tubuh yang misterius. Meski terpisah jauh, mereka yakin dan berharap bahwa suatu hari mereka akan bertemu. Kata-katanya ini mengandung pesan tentang harapan, kepercayaan, dan takdir yang merentangkan waktu dan ruang.",
  }
]